### ISSUE TITLE
Entity-based projectiles is inevitable...

### ISSUE THREAD

**Issue by ClobberXD** [ClobberXD/gunslinger#25]
While `gunslinger` uses `Deferred Raycasting` for improved realism without much of a performance hit, there are still some potential inconsistencies or edge-cases like the one below:

![screenshot_20190327_122016](https://user-images.githubusercontent.com/36130650/55056008-e2a9d280-508a-11e9-88a4-abf09cb60745.png)

Deferred Raycasting works by initially performing a raycast to obtain the distance to the point being aimed at. If the player in the screenshot is moving, the shooter has to compensate for the player's movement by shooting ahead of the player. But due to the position and angle of the shooter, the initial dummy raycast will return a pointed_thing pointing to a very distant node. This results in the delay being wrongly calculated, which means that the second and actual raycast will be performed after a wrongly-calculated delay, making this technique worse than instant-hit.

As much as I hate it, `gunslinger` would have to start using entity-based projectiles, for the sake of consistency. :|

**Comment by LoneWolfHT** [comment]
How does the shooter mod do it?

**Comment by ClobberXD** [comment]
`shooter` predicts the position of the projectile after `shooter.config.rounds_update_time`, and performs a raycast to that intermediate position. This process is repeated every `shooter.config.rounds_update_time`, until the raycast-returned pointed_thing actually points to a node or object.

See functions `fire_weapon`, `process_round`, and `process_hit` in https://github.com/stujones11/shooter/blob/master/shooter/api.lua

While this is a very neat idea, I still haven't understood the mechanics to the level required to successfully implement it in `gunslinger`. I suppose there's no harm in also trying out shooter's approach alongside the entity-based one.

**Comment by ClobberXD** [comment]
See #27

**Comment by LoneWolfHT** [comment]
Why not do a series of raycasts over time to cover the bullet's travel in steps? Maybe running a series of 5-node raycasts with slight delays in-between to let the particle catch up? At the end of each step you could change the direction very slightly in order to simulate bullet drop too

**Comment by LoneWolfHT** [comment]
Or did I just suggest what shooter does?

**Comment by ClobberXD** [comment]
That's similar to how shooter works after v6.0, and is exactly what #27 suggests. :)

**Comment by ClobberXD** [comment]
Entity-based projectiles is NOT inevitable. Screw entities. :)
