### ISSUE TITLE
Use Progressive Raycasting instead of Deferred Raycasting.

### ISSUE THREAD

**Issue by ClobberXD** [ClobberXD/gunslinger#27]
This is similar to how shooter manages to process rounds without issues like in #25. See https://github.com/ClobberXD/gunslinger/issues/25#issuecomment-477443171 to know how this works.

Once I can understand this technique better, I'll definitely give this a try. If this works, I'd definitely go with this over an entity-based approach.

**Comment by ClobberXD** [comment]
Progressive Raycasting can actually allow for much more interesting features like bullet drop and better physics overall. This is because this technique tracks the projectile in real-time, and can apply changes to the projectile on the fly (quite literally).

**Comment by afshaan4** [comment]
is there no fast and efficient way to do particles with physics for hit detection and bullet drawing?
or would that need to be supported by the engine?

**Comment by ClobberXD** [comment]
(Un)fortunately, particles are completely client-side - so virtually no load for the server. But, since the particles aren't handled server-side, they can only be created, not tracked. i.e. Mods can only issue commands to clients to add particles (or particle-spawners) with a set of attributes, but they can't actually track the particles.

Collision-detection already exists, and can be used to remove the particle upon collision. So to actually make it usable by mods, one would just have to make the client inform the server about the collision, which would hopefully trigger a callback. Not much work tbh, it just hasn't been implemented yet.

Speaking of particles, they might probably be the only fatal flaw in Progressive Raycasting. While the (imaginary) projectiles themselves can be tracked, and subsequently be subjected to various effects, the same can't be said about particles, for the aforementioned reason.

**Comment by afshaan4** [comment]
ah I see

**Comment by ClobberXD** [comment]
Primitive bullet drop should actually be possible to apply to the particle, as it can be determined when the particle is spawned.

**Comment by ClobberXD** [comment]
Progressive Raycasting is closer to becoming a reality. Brace yerselves... >:)

**Comment by ClobberXD** [comment]
#35 :tada:
